services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: nestjs-sample-sqlserver
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver-data: